### ISSUE TITLE
Using the not operator

### ISSUE THREAD

**Issue by AeroX2** [rachsug/Ebi-Game#2]
https://github.com/rachsug/Ebi-Game/blob/502fc3d21afc6b19d32da20c12115813854b31ef/scripts/sounds.js#L68

These lines could be replaced with

this.muted = !this.muted

Also when the game is muted, you stop stop the music, to stop the current sound that is playing.

**Comment by rachsug** [comment]
@AeroX2 Those lines have been replaced to use the not operator.
